-- XÓA TẤT CẢ BẢNG CŨ
DROP TABLE IF EXISTS
    vocabulary,
    question,
    flashcard,
    learning,
    learning_progress,
    lesson_rate,
    pin_clazz,
    enrollment,
    lesson,
    chapter,
    clazz
CASCADE;

-- TẠO LẠI BẢNG
CREATE TABLE clazz (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_date timestamp,
	updated_date timestamp,
	title varchar(100) not null,
	description varchar(500) not null,
	image_url varchar(500),
	author_id varchar(100) not null,
    status smallint default 1
);

CREATE TABLE chapter (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_date timestamp,
	updated_date timestamp,
	clazz_id integer not null,
	title varchar(100) not null,
	description varchar(500) not null,
	image varchar(500),
	status smallint default 2
);

CREATE TABLE lesson (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_date timestamp,
	updated_date timestamp,
	chapter_id integer,
	title varchar(100) not null,
	description varchar(500) not null,
	learning_type varchar(100) not null,
	status smallint default 2
);

CREATE TABLE learning(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_date timestamp,
	updated_date timestamp,
	lesson_id integer not null,
	type varchar(50)
);

CREATE TABLE vocabulary(
	word varchar(255),
	meaning varchar(255),
	description varchar(500),
	image varchar(500)
) INHERITS (learning);

CREATE TABLE question(
	question varchar(500),
	question_type varchar(50),
	description varchar(500),
	answer JSONB
) INHERITS (learning);

CREATE TABLE flashcard(
	front_content varchar(500) NOT NULL,
	back_content varchar(500) NOT NULL,
	front_image varchar(500),
	back_image varchar(500),
	front_extra JSONB,
	back_extra JSONB
) INHERITS (learning);

CREATE TABLE enrollment(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_date timestamp,
	updated_date timestamp,
	user_id varchar(100),
	clazz_id int,
	status smallint
);

CREATE TABLE learning_progress(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id varchar(100) not null,
	learning_id bigint not null,
	progress smallint,
	created_date timestamp,
	updated_date timestamp
);

CREATE TABLE pin_clazz (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id varchar(100) not null,
    clazz_id INTEGER,
    created_date TIMESTAMP,
    updated_date TIMESTAMP
);

CREATE TABLE lesson_rate (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id varchar(100) not null,
    lesson_id INTEGER,
    rate INTEGER,
    created_date TIMESTAMP,
    updated_date TIMESTAMP
);
