CREATE TABLE clazz (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_date timestamp,
	updated_date timestamp,
	title varchar(100) not null,
	description varchar(500) not null,
	image_url varchar(500),
	author_id integer not null
);

CREATE TABLE chapter (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_date timestamp,
	updated_date timestamp,
	clazz_id integer not null,
	title varchar(100) not null,
	description varchar(500) not null,
	image varchar(500),
	status smallint default 2
);

CREATE TABLE lesson (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_date timestamp,
	updated_date timestamp,
	chapter_id integer,
	title varchar(100) not null,
	description varchar(500) not null,
	learning_type varchar(100) not null
);

CREATE TABLE learning(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_date timestamp,
	updated_date timestamp,
	lesson_id integer not null,
	type varchar(50)
);

CREATE TABLE vocabulary(
	word varchar(255),
	meaning varchar(255),
	description varchar(500),
	image varchar(500)
) INHERITS (learning);

CREATE TABLE question(
	question varchar(500),
	question_type varchar(50),
	answer JSONB
) INHERITS (learning);

CREATE TABLE flashcard(
	front_content varchar(500) NOT NULL,
	back_content varchar(500) NOT NULL,
	front_image varchar(500),
	back_image varchar(500),
	front_extra JSONB,
	back_extra JSONB
) INHERITS (learning);
 




